// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdI4Q_j0H_QMEkV_ELocN4lwuOr6nOHhM',
    appId: '1:997374089352:web:bc8c07ad67a06fe73ae73d',
    messagingSenderId: '997374089352',
    projectId: 'resqai-caf4a',
    authDomain: 'resqai-caf4a.firebaseapp.com',
    storageBucket: 'resqai-caf4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5K5ZYLP566JiOkAnjRse1gj_YtN1jyM',
    appId: '1:997374089352:android:ae458a3bda34206b3ae73d',
    messagingSenderId: '997374089352',
    projectId: 'resqai-caf4a',
    storageBucket: 'resqai-caf4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhydtlUky8JfjR-tOuLV0tDFWTZDmgr8',
    appId: '1:997374089352:ios:702aa96e650d193f3ae73d',
    messagingSenderId: '997374089352',
    projectId: 'resqai-caf4a',
    storageBucket: 'resqai-caf4a.firebasestorage.app',
    iosBundleId: 'com.example.resqai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXhydtlUky8JfjR-tOuLV0tDFWTZDmgr8',
    appId: '1:997374089352:ios:702aa96e650d193f3ae73d',
    messagingSenderId: '997374089352',
    projectId: 'resqai-caf4a',
    storageBucket: 'resqai-caf4a.firebasestorage.app',
    iosBundleId: 'com.example.resqai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdI4Q_j0H_QMEkV_ELocN4lwuOr6nOHhM',
    appId: '1:997374089352:web:cc8391accdbbe1723ae73d',
    messagingSenderId: '997374089352',
    projectId: 'resqai-caf4a',
    authDomain: 'resqai-caf4a.firebaseapp.com',
    storageBucket: 'resqai-caf4a.firebasestorage.app',
  );
}
